### ISSUE TITLE
MediaRecorder doesn't work if we add the audioMixAllStream track

### ISSUE THREAD

**Issue by ldenoue** [mganeko/browser_mcu_server#3]
I'm trying to also record the audio and video produced by the MCU using a MediaRecorder.
It works when I only set it to use the mixStream (CANVAS stream), but as soon as I add the audioMixAllStream audio track (see https://github.com/mganeko/browser_mcu_core/blob/07f03ae5e6720abbf57862adc9395a85ff6fff99/js/browser_mcu_core.js#L140 ) my recorder does not fire any data.

Do we need to start the AudioContext in some ways?

Laurent

**Comment by mganeko** [comment]
Hi, thanks for you trial.

Recently browsers have "Autoplay policy", so we need user gesture before using AudioContext.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Best_practices

Please try "--autoplay-policy=no-user-gesture-required" command line option to invoke headless chrome.
( headlessArgs:  of options.js )
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

If it doesn't work, I have no idea now.

**Comment by ldenoue** [comment]
You were right! That extra parameter allows creating the audio context.
I'm using Puppeteer now, so I start the browser this way:
`const browser = await puppeteer.launch({ignoreHTTPSErrors:true, args: ['--no-sandbox','--autoplay-policy=no-user-gesture-required']});`

I also had to modify something else: in https://github.com/mganeko/browser_mcu_core/blob/07f03ae5e6720abbf57862adc9395a85ff6fff99/js/browser_mcu_core.js#L550 I commented out your for loop block and added the new remote micNode to the mixAllAudioNode, otherwise we don't get audio in the final video produced by the MediaRecorder.

So my code looks like this:
```
  this.addRemoteAudioMinusOne = function (peerId, stream) {
    let audioTracks = stream.getAudioTracks();
    if (audioTracks && (audioTracks.length > 0)) {
      console.log('stream has audioStream. audio track count = ' + audioTracks.length);
      console.log(' stream.id=' + stream.id + ' , track.id=' + audioTracks[0].id);

      // --- prepare audio mic node ---
      let micNode = audioContext.createMediaStreamSource(stream);
      inputNodes[peerId] = micNode;

      // Laurent
      micNode.connect(mixAllOutputNode);
      /*// --- connect to other output ---
      for (let key in minusOneOutputNodes) {
        if (key === peerId) {
          console.log('skip output(id=' + key + ') because same id=' + peerId);
        }
        else {
          let otherOutputNode = minusOneOutputNodes[key];
          micNode.connect(otherOutputNode);
          //alert('here');
        }
      }*/
    }
    else {
      console.warn('NO Audio Tracks in stream');
    }
  }
```

**Comment by mganeko** [comment]
Great! 

This example is for meeting.
If you want to mix all audio for recording, please use BrowserMCU.AUDIO_MODE_ALL .
https://github.com/mganeko/browser_mcu_core#mix-all-audio-for-recording

```
mcu.setAudioMode(BrowserMCU.AUDIO_MODE_ALL);
```

**Comment by mganeko** [comment]
Anyway, close this issue.
